### ISSUE TITLE
Demo should include API usage examples

### ISSUE THREAD

**Issue by jchazalon** [EPITAResearchLab/bernet.23.icdar#1]
Currently, the `demo/demo.ipynb` notebook only contains the qualitative tuning tool, which is great but not very useful for potential users who want to use our Python bindings.

I think we should add some examples which illustrate how to produce and use the different kinds of outputs for a given input image.

@Sefray what would you think about this?

**Comment by Sefray** [comment]
Currently, there are no python bindings (not yet)

To use the line detector in python code, you should use a subprocess.call with the CLI argument.

Some examples can indeed me added

**Comment by jchazalon** [comment]
When Python bindings are ready, we'd like to have:

- `demo/demo.ipynb` which contains a very basic Python demo which loads and processes the images as shown in the README file
- `demo/demo_interactive.ipynb` which contains the previously named "demo.ipynb" content.
