### ISSUE TITLE
Add link to download dataset

### ISSUE THREAD

**Issue by jchazalon** [EPITAResearchLab/bernet.23.icdar#2]
`README.md` should contain a link to download the dataset, to enable to reproduce the results.

For the record, here is what we shared with reviewers for the double-blind review: https://osf.io/u5wmh/?view_only=454a1539f1e648e7bfed7dd754128260

**Comment by Sefray** [comment]
Link has been added in the README : [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.7927611.svg)](https://doi.org/10.5281/zenodo.7927611)
